lista_compras/compras/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('nova/', views.nova_lista, name='nova_lista'),
    path('lista/<int:lista_id>/', views.lista_compras, name='lista_compras'),
    path('lista/<int:lista_id>/', views.deletar_lista, name='deleta'),

    path('lista/<int:lista_id>/comprado/<int:item_id>/', views.marcar_comprado, name='comprado'),
    path('deletar-lista/<int:lista_id>/', views.deletar_lista, name='deletar_lista'),
]    

lista_compras/lista_compras/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('compras.urls')),
    
]

lista_compras/compras/models.py
from django.db import models

# Create your models here.
class Lista_compras(models.Model):
    nome = models.CharField(max_length=100)
    craido_em = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome

class Item(models.Model):
    lista = models.ForeignKey(Lista_compras, on_delete=models.CASCADE, related_name='itens')
    nome = models.CharField(max_length=100)
    comprado = models.BooleanField(default=False)
    criado_em = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome

lista_compras/compras/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Item, Lista_compras

# Create your views here.
def lista_compras(request, lista_id=0):
    lista = get_object_or_404(Lista_compras, id=lista_id) #lista recebe os objetos diretos da lista_compras pelo seu id, se nao encontrar ele exibe uma pagina de erro 404 automaticamente.
    itens = lista.itens.all().order_by('-criado_em') #itens recebe uma todos os itens da lista por ordem de cricação.

    #Se o usuario enviou um formulario do tipo POST.
    if request.method == 'POST':
        nome = request.POST.get('nome', '').strip() #pega o valor digitado no formulario(pagina html) pelo usuario.
        if nome: #Se foi colocado algum nome no formulario, ele será craido e depois a pagina sera redirecionada para lista.
            Item.objects.create(nome=nome, lista_id=lista_id)
            return redirect('lista_compras', lista_id=lista_id)
    
    return render(request, 'compras/lista.html', {'itens': itens, 'lista': lista}) 


#funçao para deletar uma lista criada.
def deletar_lista(request, lista_id):
    lista = get_object_or_404(Lista_compras, id=lista_id) #lista recebe a lista pelo id.
    lista.delete() #lista acessa o banco de dados para deletar usando o id que foi salvo em lista.
    return redirect('home')

"""def listas(request): #função para retornar todas as listas.
    listas = Lista_compras.objects.all().order_by('-criado_em') #listas vai receber de Listas_compras importadas do models, todos os objetos por ordem de criação('-criada_em')
    return render(request, 'compras/lista.html', {'listas': listas}) #retornando o caminho de onde esntão todas as listas."""

#funcao para criar uma nova lista.
def nova_lista(request):
    if request.method == 'POST': #se a requisição tiver o metodo post ele vai receber o nome informado no formulario.
        nome = request.POST.get('nome', '').strip()
        if nome: #Se tiver algum nome no formulario ele vai acionar o listas_compras do model e criar um nome para a lista.
            Lista_compras.objects.create(nome=nome)
            return redirect('home')
        
    return render(request, 'compras/nova_lista.html')

def home(request):
    listas = Lista_compras.objects.all()
    return render(request, 'compras/home.html', {'listas':listas})




# Recebe da requiseção o item/id escolhido e acessa o medel fazendo a exclusão do item.
def deletar_item(request, lista_id, item_id):
    item = get_object_or_404(Item, id=item_id, lista_id=lista_id)
    item.delete()
    return redirect('lista_compras', lista_id=lista_id)

def marcar_comprado(request, lista_id, item_id):
    item = get_object_or_404(Item, id=item_id, lista_id=lista_id)
    item.comprado = not item.comprado #muda a situação do item.comprado, se for False muda para True.
    item.save() #salva a alteração feita no banco de dados.
    return redirect('lista_compras', lista_id=lista_id) #apos salvar ele redireciona para a pagina lista(que a pagina inicial)

lista_compras/compras/templates/compras/home.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Minhas Listas de Compras</title>
</head>
<body>
    <h1>Minhas Listas de Compras 📝</h1>

    <a href="{% url 'nova_lista' %}">
        <button style="background-color: #28a745; color: white; border: none; padding: 10px; cursor: pointer;">
            + Criar Nova Lista
        </button>
    </a>

    <hr>

    <ul>
        {% for lista in listas %}
            
                <li style="margin-bottom: 10px;">
                    <strong>
                        <a href="{% url 'lista_compras' lista.id %}">{{ lista.nome }}</a>
                    </strong>
                    <small>(Criada em: {{ lista.criada_em|date:"d/m/Y" }})</small>
                    <a href=" {% url 'deletar_lista' lista.id  %} "> ❌ </a>
                </li>
           
         {% empty %}
            <li>Você ainda não criou nenhuma lista.</li>

        {% endfor %}
    </ul>

</body>
</html>

lista_compras/compras/templates/compras/lista.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Lista de Compras </title>
</head>
<body>
    <h1> 🛒 {{ lista.nome }} </h1>

    <form method="post">
        {% csrf_token %}
        <input type="text" name="nome" placeholder="Novo_item" required>
        <button type="submit"> Adicionar </button>
     </form>

     <ul>
        {% for item in itens %}
            <li>
                {% if item.comprado %}
                    <s> {{item.nome}} </s>
                {% else %}
                    {{item.nome}}
                {% endif %}

                <a href=" {% url 'comprado' lista.id item.id %} "> ✔ </a>
                <a href=" {% url 'deletar' lista.id item.id %} "> ❌ </a>

            </li>
        {% empty %}
            <li> Nenhum item nesta lista. </li>
        {% endfor %}

    </ul>

    
</body>
</html>

lista_compras/compras/templates/compras/nova_lista.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criar Nova Lista</title>
</head>
<body>
    <h1>Criar Nova Lista de Compras 🆕</h1>

    <form method="post">
        {% csrf_token %}
        <label for="id_nome">Nome da Lista:</label>
        <input type="text" name="nome" id="id_nome" placeholder="Ex: Mercado, Feira..." required>
        
        <button type="submit">Salvar Lista</button>
        
    </form>

    <br>
    <a href="{% url 'home' %}">⬅ Voltar para minhas listas</a>

</body>
</html>